# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Pseudorandom numbers from a Gaussian distribution that is truncated to an interval.
#' 
#' @param lower lower bound of truncation interval
#' @param upper upper bound of truncation interval
#' @param mu mean of the normal random variable (before truncation)
#' @param sigma standard deviation of the normal random variable (before truncation)
#' @export
rtnorm <- function(lower, upper, mu, sigma) {
    .Call(`_RMTRCode2_rtnorm`, lower, upper, mu, sigma)
}

